version: '3.8'

services:
  user_service:
    container_name: user_service
    build: 
      context: ./user_service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=go_tugasakhir
      - DB_PORT=3306
    networks:
      - simta_net

  document_service:
    container_name: document_service
    build:
      context: ./document_service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=go_tugasakhir
      - DB_PORT=3306
    volumes:
      - ./document_service/uploads:/app/uploads
    networks:
      - simta_net

  ta_service:
    container_name: ta_service
    build: 
      context: ./ta_service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=go_tugasakhir
      - DB_PORT=3306
    networks:
      - simta_net

networks:
  simta_net:
    driver: bridge

volumes:
  mysql_data:
    driver: local
