addOns:
  install:
    - reports

env:
  contexts:
    - name: SIMTA
      urls: ["https://securesimta.my.id"]
      includePaths:
        - "^https?://securesimta\\.my\\.id/taruna/.*"
        - "^https?://securesimta\\.my\\.id($|/.*)"
      excludePaths:
        - "^https?://securesimta\\.my\\.id/logout.*"
        - ".*\\.(png|jpe?g|svg|gif|css|js|ico|woff2?|pdf|zip)$"
      authentication: { method: manual }
      sessionManagement: { method: http }
      users: []

parameters:
  failOnError: true
  progressToStdout: true

scripts:
  - name: jwt_taruna
    type: httpsender
    engine: "ECMAScript : Graal.js"
    file: /zap/wrk/jwt-taruna.js
    enabled: true

jobs:
  # 2.1 Paksa ada 1 request terautentikasi untuk memicu doLogin()
  - type: requestor
    requests:
      - { url: "https://securesimta.my.id/",                 method: "GET" }
      - { url: "https://securesimta.my.id/loginusers",       method: "GET" }
      - { url: "https://securesimta.my.id/taruna/dashboard", method: "GET" }

  # 2.2 Tunggu passive scanner sebentar (opsional)
  - type: passiveScan-wait
    parameters: { maxDuration: 2 }

  # 2.3 Baru Spider (sekarang sudah logged-in)
  - type: spider
    parameters:
      context: SIMTA
      url: "https://securesimta.my.id/taruna/dashboard"
      maxChildren: 0
      maxDuration: 15
      acceptCookies: true
      postForm: true
      parseComments: true
      parseRobotsTxt: true
      parseSitemapXml: true

  # Active scan setelah crawling
  - type: activeScan
    parameters:
      context: SIMTA
      policy: "Taruna"
      addQueryParam: true
      scanHeadersAllRequests: true
      maxRuleDurationInMins: 10

  # # Passive scan lagi setelah active scan
  # - type: passiveScan-wait
  #   parameters: { maxDuration: 2 }

  # Report ke lokasi lama yang berhasil
  - type: report
    parameters:
      template: traditional-html
      reportFile: zap-report.html
      reportDir: /home/zap/.ZAP/reports
      displayReport: false
  - type: report
    parameters:
      template: traditional-json
      reportFile: zap-results.json
      reportDir: /home/zap/.ZAP/reports
      displayReport: false
