addOns:
  install:
    - reports

env:
  contexts:
    - name: SIMTA
      urls: ["https://securesimta.my.id"]
      includePaths:
        - "^https?://securesimta\\.my\\.id/taruna/.*"
      excludePaths:
        - "^https?://securesimta\\.my\\.id/logout.*"
        - ".*\\.(png|jpe?g|svg|gif|css|js|ico|woff2?|pdf|zip)$"
      authentication: { method: manual }
      sessionManagement: { method: http }
      users: []

parameters:
  failOnError: true
  progressToStdout: true

scripts:
  - name: jwt_taruna.js
    type: httpsender
    engine: "ECMAScript : Graal.js"
    file: /zap/wrk/jwt-taruna.js
    enabled: true

jobs:
  # Seed awal (opsional, tambahkan jika mau langsung buka URL ini)
  - type: requestor
    requests:
      - { url: "https://securesimta.my.id/taruna/dashboard", method: "GET" }
      - { url: "https://securesimta.my.id/taruna/icp", method: "GET" }
      - { url: "https://securesimta.my.id/taruna/proposal", method: "GET" }
      - { url: "https://securesimta.my.id/taruna/ta70", method: "GET" }
      - { url: "https://securesimta.my.id/taruna/ta100", method: "GET" }

  # Spider klasik saja
  - type: spider
    parameters:
      context: SIMTA
      url: "https://securesimta.my.id/taruna/dashboard"
      maxChildren: 0

  # Passive scan setelah spider
  - type: passiveScan-wait
    parameters: { maxDuration: 2 }

  # Active scan setelah crawling
  - type: activeScan
    parameters:
      context: SIMTA
      policy: "Taruna"
      addQueryParam: true
      scanHeadersAllRequests: true
      maxRuleDurationInMins: 10

  # Passive scan lagi setelah active scan
  - type: passiveScan-wait
    parameters: { maxDuration: 2 }

  # Report ke lokasi lama yang berhasil
  - type: report
    parameters:
      template: traditional-html
      reportFile: zap-report.html
      reportDir: /home/zap/.ZAP/reports
      displayReport: false
  - type: report
    parameters:
      template: traditional-json
      reportFile: zap-results.json
      reportDir: /home/zap/.ZAP/reports
      displayReport: false
