addOns:
  install:
    - reports

env:
  contexts:
    - name: SIMTA
      urls: ["https://securesimta.my.id"]
      includePaths: ["https://securesimta.my.id.*"]
      excludePaths:
        - ".*\\.(png|jpg|jpeg|gif|svg|webp|ico|css|woff2?)$"
      authentication: { method: manual }
      sessionManagement: { method: cookie }
      users: []

parameters:
  failOnError: true
  progressToStdout: true

scripts:
  - name: jwt_taruna
    type: httpsender
    engine: "ECMAScript : Graal.js"
    file: /zap/wrk/jwt-taruna.js
    enabled: true

jobs:
  - type: passiveScan-wait
    parameters: { maxDuration: 1 }

  # (1) Crawl publik (opsional)
  - type: spider
    parameters:
      context: SIMTA
      url: "https://securesimta.my.id"
      maxDuration: 5
      maxDepth: 10
      parseRobotsTxt: true
      parseSitemapXml: true

  # (2) Pancing login + akses halaman proteksi
  - type: requestor
    parameters:
      title: "Seed logged-in area (Taruna)"
      followRedirects: true
    requests:
      # GET ke dashboard akan memicu script JWT melakukan login() dan menempelkan Authorization otomatis
      - url: "https://securesimta.my.id/taruna/dashboard"
        method: "GET"

  # (3) Spider dari dashboard Taruna (sudah login)
  - type: spider
    parameters:
      context: SIMTA
      url: "https://securesimta.my.id/taruna/dashboard"
      maxDuration: 5
      maxDepth: 15
      recurse: true
      parseRobotsTxt: false
      parseSitemapXml: false
      subtreeOnly: true

  # (4) Active Scan
  - type: activeScan
    parameters:
      context: SIMTA
      policy: Default Policy
      maxRuleDurationInMins: 10
      addQueryParam: true

  # (5) Reports
  - type: report
    parameters: { template: traditional-html,  reportFile: zap-report.html,  reportDir: /home/zap/.ZAP/reports, displayReport: false }
  - type: report
    parameters: { template: traditional-json, reportFile: zap-results.json, reportDir: /home/zap/.ZAP/reports, displayReport: false }
