addOns:
  install:
    - reports
    - spiderAjax
    - webdriverlinux

env:
  contexts:
    - name: SIMTA
      urls: ["https://securesimta.my.id"]
      includePaths:
        - "^https?://securesimta\\.my\\.id($|/.*)"
      authentication: { method: manual }
      sessionManagement: { method: http }
      users: []

parameters:
  failOnError: true
  progressToStdout: true

scripts:
  - name: jwt_taruna
    type: httpsender
    engine: "ECMAScript : Graal.js"
    file: /zap/wrk/jwt-taruna.js
    enabled: true

jobs:
  - type: passiveScan-wait
    parameters: { maxDuration: 1 }

  # seed halaman yg kamu klik di GUI
  - type: requestor
    requests:
      - { url: "https://securesimta.my.id/taruna/dashboard", method: "GET" }
      - { url: "https://securesimta.my.id/taruna/icp",       method: "GET" }
      - { url: "https://securesimta.my.id/taruna/proposal",  method: "GET" }
      - { url: "https://securesimta.my.id/taruna/ta70",      method: "GET" }
      - { url: "https://securesimta.my.id/taruna/ta100",     method: "GET" }

  # AJAX Spider (paksa jalan)
  - type: spiderAjax
    parameters:
      context: SIMTA
      url: "https://securesimta.my.id/taruna/dashboard"
      maxDuration: 15
      maxCrawlDepth: 6
      numberOfBrowsers: 2
      runOnlyIfModern: false
      browserId: "chrome"
      clickElemsOnce: true
      randomInputs: true

  # Active Scan dengan policy GUI kamu
  - type: activeScan
    parameters:
      context: SIMTA
      policy: "Taruna"            # <- nama file policy tanpa ekstensi
      maxRuleDurationInMins: 10
      addQueryParam: true

  - type: report
    parameters: { template: traditional-html, reportFile: zap-report.html,  reportDir: /home/zap/.ZAP/reports, displayReport: false }
  - type: report
    parameters: { template: traditional-json, reportFile: zap-results.json, reportDir: /home/zap/.ZAP/reports, displayReport: false }
