addOns:
  install:
    - reports

env:
  contexts:
    - name: SIMTA
      urls: ["https://securesimta.my.id"]
      includePaths: ["https://securesimta.my.id.*"]
      authentication: { method: manual }
      sessionManagement: { method: cookie }
      users: []

parameters:
  failOnError: true
  progressToStdout: true

scripts:
  - name: jwt_taruna
    type: httpsender
    engine: "ECMAScript : Graal.js"
    file: /zap/wrk/jwt-taruna.js
    enabled: true

jobs:
  - type: passiveScan-wait
    parameters: { maxDuration: 1 }

  # Crawl publik
  - type: spider
    parameters:
      context: SIMTA
      url: "https://securesimta.my.id"
      maxDuration: 5
      maxDepth: 10
      parseRobotsTxt: true
      parseSitemapXml: true

  # Pancing login (script JWT akan login otomatis)
  - type: requestor
    requests:
      - url: "https://securesimta.my.id/taruna/dashboard"
        method: "GET"

  # (opsional) Spider dari dashboard untuk menambah cakupan
  - type: spider
    parameters:
      context: SIMTA
      url: "https://securesimta.my.id/taruna/dashboard"
      maxDuration: 5
      maxDepth: 15
      parseRobotsTxt: false
      parseSitemapXml: false

  - type: activeScan
    parameters:
      context: SIMTA
      policy: Default Policy
      maxRuleDurationInMins: 10
      addQueryParam: true

  - type: report
    parameters: { template: traditional-html,  reportFile: zap-report.html,  reportDir: /home/zap/.ZAP/reports, displayReport: false }
  - type: report
    parameters: { template: traditional-json,  reportFile: zap-results.json,  reportDir: /home/zap/.ZAP/reports, displayReport: false }
