parameters:
  failOnError: true
  progressToStdout: true

contexts:
  - name: SIMTA
    urls: ["https://securesimta.my.id"]
    includePaths: ["https://securesimta.my.id.*"]
    excludePaths:
      - ".*\\.(png|jpg|jpeg|gif|svg|webp|ico|css|woff2?)$"
    authentication: { method: manual }
    sessionManagement: { method: cookie }
    users: []

scripts:
  - name: jwt_taruna
    type: httpsender
    engine: "ECMAScript : Graal.js"
    file: /zap/wrk/jwt-taruna.js   # <-- pastikan sama dengan nama file di repo
    enabled: true

jobs:
  - type: passiveScan-wait
    parameters: { maxDuration: 1 }

  - type: spider
    parameters:
      context: SIMTA
      url: "https://securesimta.my.id"
      maxDuration: 5        # menit
      maxDepth: 10
      parseRobotsTxt: true
      parseSitemapXml: true

  - type: activeScan
    parameters:
      context: SIMTA
      policy: Default Policy
      maxRuleDurationInMins: 10
      addQueryParam: true

  - type: report
    parameters: { template: traditional-html,  reportFile: zap-report.html,  reportDir: /zap/wrk, displayReport: false }
  - type: report
    parameters: { template: traditional-md,    reportFile: zap-report.md,    reportDir: /zap/wrk, displayReport: false }
  - type: report
    parameters: { template: traditional-json,  reportFile: zap-results.json, reportDir: /zap/wrk, displayReport: false }
