addOns:
  install:
    - reports

env:
  contexts:
    - name: SIMTA
      urls: ["https://securesimta.my.id"]
      includePaths:
        - "^https?://securesimta\\.my\\.id/taruna/.*"
      excludePaths:
        - "^https?://securesimta\\.my\\.id/logout.*"
        - ".*\\.(png|jpe?g|svg|gif|css|js|ico|woff2?|pdf|zip)$"
      authentication: { method: manual }   # pakai HTTP Sender (JWT)
      sessionManagement: { method: http }
      users: []

parameters:
  failOnError: true
  progressToStdout: true

scripts:
  - name: jwt_taruna.js
    type: httpsender
    engine: "ECMAScript : Graal.js"
    file: /zap/wrk/jwt-taruna.js
    enabled: true

jobs:
  # Seed manual (opsional)
  - type: requestor
    requests:
      - { url: "https://securesimta.my.id/taruna/dashboard", method: "GET" }

  # Spider klasik saja
  - type: spider
    parameters:
      context: SIMTA
      url: "https://securesimta.my.id/taruna/dashboard"
      maxChildren: 0           # 0 = tanpa batas

  # Tunggu passive scanner memproses hasil spider
  - type: passiveScan-wait
    parameters: { maxDuration: 2 }

  # Active Scan setelah crawling selesai (biar ada temuan)
  - type: activeScan
    parameters:
      context: SIMTA
      policy: "Taruna"         # atau "Default Policy" kalau perlu uji cepat
      addQueryParam: true
      scanHeadersAllRequests: true
      maxRuleDurationInMins: 10

  # Tunggu passive scanner lagi (hasil active juga dipassive-scan)
  - type: passiveScan-wait
    parameters: { maxDuration: 2 }

  # Report ke folder kerja yang dimount
  - type: report
    parameters:
      template: traditional-html
      reportFile: zap-report.html
      reportDir: /zap/wrk/reports
      displayReport: false
  - type: report
    parameters:
      template: traditional-json
      reportFile: zap-results.json
      reportDir: /zap/wrk/reports
      displayReport: false
