addOns:
  install:
    - reports
    - spiderAjax
    - webdriverlinux

env:
  contexts:
    - name: SIMTA
      urls:
        - "https://securesimta.my.id"
      includePaths:
        - "^https?://securesimta\\.my\\.id($|/.*)"  # cover semua path & /api/*
      authentication: { method: manual }
      sessionManagement: { method: http }
      users: []

parameters:
  failOnError: true
  progressToStdout: true

scripts:
  - name: jwt_taruna
    type: httpsender
    engine: "ECMAScript : Graal.js"
    file: /zap/wrk/jwt-taruna.js
    enabled: true

jobs:
  - type: passiveScan-wait
    parameters: { maxDuration: 1 }

  # Seed halaman setelah login; ini akan memicu doLogin() dari script JWT
  - type: requestor
    requests:
      - url: "https://securesimta.my.id/taruna/dashboard"
        method: "GET"
      - url: "https://securesimta.my.id/taruna/icp"
        method: "GET"
      - url: "https://securesimta.my.id/taruna/proposal"
        method: "GET"
      - url: "https://securesimta.my.id/taruna/ta70"
        method: "GET"
      - url: "https://securesimta.my.id/taruna/ta100"
        method: "GET"

  # HANYA Ajax Spider (paksa jalan)
  - type: spiderAjax
    parameters:
      context: SIMTA
      url: "https://securesimta.my.id/taruna/dashboard"
      maxDuration: 15
      maxCrawlDepth: 6
      numberOfBrowsers: 2
      runOnlyIfModern: false     # <- penting: jangan di-skip lagi
      # (opsional) stabilkan browser headless
      browserId: "chrome"
      clickElemsOnce: true
      randomInputs: true

  - type: activeScan
    parameters:
      context: SIMTA
      policy: "Default Policy"
      maxRuleDurationInMins: 10
      addQueryParam: true

  - type: report
    parameters: { template: traditional-html, reportFile: zap-report.html,  reportDir: /home/zap/.ZAP/reports, displayReport: false }
  - type: report
    parameters: { template: traditional-json, reportFile: zap-results.json, reportDir: /home/zap/.ZAP/reports, displayReport: false }
